spring.config.import=optional:file:.env[.properties]

spring.application.name=url-shortener

spring.datasource.url=${spring.datasource.url}
spring.datasource.username=${username}
spring.datasource.password=${password}
spring.jpa.properties.hibernate.dialect=${database_dialect}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${jwt_secret} 
jwt.expiration=${jwt_expiration}

logging.level.org.springframework.security=DEBUG
logging.level.org.url_shortener=DEBUG
logging.level.org.springframework.web.servlet=TRACE

frontend.url=${frontend_url}